$(document).on 'turbolinks:load', ->
  initStickyAdd = ->
    $(window).on 'scroll', ->
      scroll = $(window).scrollTop()
      if scroll >= 50
        $('.sticky').addClass 'stickyadd'
      else
        $('.sticky').removeClass 'stickyadd'
      return
    return

  initSmoothNav = ->
    $('.navbar-nav a').on 'click', (event) ->
      $anchor = $(this)
      $('html, body').stop().animate { scrollTop: $($anchor.attr('href')).offset().top - 0 }, 1500, 'easeInOutExpo'
      event.preventDefault()
      return
    return

  initScrollspy = ->
    $('#navbarCollapse').scrollspy offset: 20
    return

  init = ->
    initStickyAdd()
    initSmoothNav()
    initScrollspy()
    return

  # 'use strict'
  # $(window).on 'scroll', ->
  #   if $(this).scrollTop() > 100
  #     $('.back_top').fadeIn()
  #   else
  #     $('.back_top').fadeOut()
  #   return
  # $('.back_top').on 'click', ->
  #   $('html, body').animate { scrollTop: 0 }, 1000
  #   false
  # $('.img-zoom').magnificPopup
  #   type: 'image'
  #   closeOnContentClick: true
  #   mainClass: 'mfp-fade'
  #   gallery:
  #     enabled: true
  #     navigateByImgClick: true
  #     preload: [
  #       0
  #       1
  #     ]
  # init()
  # return
# ---
# generated by js2coffee 2.2.0
